### ISSUE TITLE
create docker build images

### ISSUE THREAD

**Issue by GreenGary** [mbsim-env/fmatvec#3]
I see two use cases for docker images within fmatvec project:
1.  Continuous integration
2.  Very concise, declarative way to describe prerequisites for building the software.

I admit, that I do not have enough insights into the current build process to decide, whether docker makes sense (or if it is even already in use). 
But imho, it would definitely lower the bar for new users/contributors. Even if not using docker itself, the Dockerfile can be used as blueprint on how to setup a working build environment.
I have prepared two files at the moment, one targets debian:buster, the other target centos7. 

If you think docker images make sense, I can share the Dockerfiles I have already created in my private fork of this project.

**Comment by friedrichatgc** [comment]
Their are no docker images for a stand-alone fmatvec build since for now their was no use case for fmatvec outside of MBSim. Docker is a great way to build and distribute programs/services but I don't see docker very useful to build libraries, except the noted use-case as a blueprint for the build setup.

However, the complete nightly build/test and CI framework for the MBSim-Environment (https://www.mbsim-env.de) is based on docker images: the web server, the build image, webgui image, ...
The build/CI runs, based on these docker images, on a hosted VM. Running it on free CI systems (like circleci, ...) is not possible since MBSim-Env is too large (loo long build/test times when running from scratch).
The complete docker setup for the build system is available at https://github.com/mbsim-env/build.
The file https://github.com/mbsim-env/build/blob/master/README.md describes also an easy way (2-3 commands) to build everything locally using docker (fmatvec and everything else).

So I don't see a need for a docker image for a stand-alone fmatvec build.

**Comment by GreenGary** [comment]
Hi Markus, thanks for the elaborate answer. I was not aware of the existing infrastructure. I think, there is no need to change anything for fmatvec wrt. docker.
